### ISSUE TITLE
clusterwise FWE

### ISSUE THREAD

**Issue by sjgershm** [spunt/bspmview#12]
I've noticed that clusterwise FWE correction doesn't seem to be working properly. When I select clusterwise correction, it doesn't appear to change the results from the uncorrected threshold.

**Comment by spunt** [comment]
It's possible I'm not understanding what you're seeing, but if by "uncorrected threshold" you mean the voxelwise height threshold (e.g., the values in the "Thresh" and "P-Value" edit boxes), then this would be the expected behavior. Clusterwise FWE uses the existing uncorrected threshold for the cluster-forming threshold, computes the minimum cluster size necessary for clusterwise FWE correction, and then automatically populates the "Extent" edit box with the resulting value.  If this isn't what is happening, perhaps you can give me more information about the data you're working with and we can go from there.
