### ISSUE TITLE
Switching off of Cluster FWE correction back to None doesn't seem responsive

### ISSUE THREAD

**Issue by jttrs** [spunt/bspmview#7]
Once I apply Cluster FWE, I can't seem to get it to revert to back to None via the pull-down.  It says None is selected, but the data visualized don't reflect the change.  Resetting the overlay works.

**Comment by spunt** [comment]
This was an intentional move on my part given that "None" isn't associated with any specific set of parameters that need to be calculated and filled in, and as you note you can reset to the default uncorrected threshold and extent using the reload overlay menu. I actually think the best move may be to get rid of the "None" option in that menu entirely, and just have the menu display either the prompt "Apply correction..." when no correction is set, and only offer the choice between cluster and voxelwise FWE. Maybe a reset button next to that field would be most intutive?

**Comment by jttrs** [comment]
Reset button seems like a good idea.  I was thinking the 'None' option should have a similar function (if it is kept) where all it really does is reset the cluster extent or t-thresh back to some starting value (like how xjview always opens up at pval .001 and k-extent 5).

Having it there like it is right now makes it seem broken even though it is working exactly as intended: as a placeholder until some correction is actually applied.

It might even help to have the pull-down menu 'pop' back to 'None' or 'Apply correction...' as soon as someone messes with the t-threst/pval/k-extent after applying a correction (k-extent for cluster, pval/t-thresh for voxel).
